api:
  id: "xxxxxxx"
http:
  port: "443"
  path: /*
  responseTimeout: "10000"
request:
  host: anypoint.mulesoft.com
  port: "443"
  path: "/exchange/portals/accenture-83335/"
  protocol: HTTPS
  api.parser: AUTO
vanity:
  domain: "developers.souldofworld.work"
  path: "/"